"""Methodology & validation -- proves the data is sound and shows provenance."""
from fastapi import APIRouter

from ..cache import cached_fetch_all as fetch_all
from ..config import DATASET_SEED
from ..schemas import Methodology, Provenance, ValidationCheck, ViewLogic

router = APIRouter(prefix="/api/methodology", tags=["methodology"])

PROVENANCE = {
    "source": "Synthetic, generated by a seeded Python model (generate_factory_data.py).",
    "no_proprietary_data": True,
    "seed": DATASET_SEED,
    "reproducible": "Re-running the generator reproduces the dataset byte-for-byte.",
    "modeling": [
        "Weibull time-to-failure per asset class (wear-out, beta>1)",
        "Shift/crew variance with a night-shift handoff penalty",
        "Defect propagation: origin station vs detection station",
        "Year-over-year seasonal severity (no two summers alike)",
        "Robot replacements that reset the fault clock",
        "Permanent process changes + a model-year launch (event rediscovery)",
    ],
    "oee_definition": (
        "OEE = Availability x Performance x Quality. "
        "Availability = (planned_time - downtime) / planned_time; "
        "Quality = good_units / produced_units; "
        "Performance = produced / (planned * Availability). "
        "Identity check: OEE == good_units / planned_units."
    ),
}

# Backing views shown on the methodology panel. The actual DDL is read from the
# database at request time via pg_get_viewdef, so the "logic" shown to reviewers
# is the real SQL the dashboard runs -- not a hand-written summary that can drift.
BACKING_VIEWS = [
    ("Executive KPIs", "v_kpi_overall"),
    ("OEE", "v_oee"),
    ("Loss by station", "v_loss_by_station"),
    ("MTTR by crew", "v_mttr_by_crew"),
    ("Root-cause ranking", "v_rootcause_ranking"),
    ("Defect propagation", "v_propagation"),
    ("Replacement candidates", "v_robot_candidates"),
    ("Validation checks", "v_validation"),
]


@router.get("/validation", response_model=list[ValidationCheck])
async def validation():
    """Row counts, referential-integrity checks, and reconciliation results."""
    return await fetch_all("SELECT check_name, v AS value, status FROM v_validation ORDER BY ord")


@router.get("/provenance", response_model=Provenance)
async def provenance():
    return PROVENANCE


@router.get("/views", response_model=list[ViewLogic])
async def views():
    """Real SQL DDL for each backing view, read live from the database."""
    out = []
    for section, view in BACKING_VIEWS:
        rows = await fetch_all(
            "SELECT pg_get_viewdef($1::regclass, true) AS logic", view
        )
        out.append({"section": section, "logic": rows[0]["logic"] if rows else ""})
    return out


@router.get("", response_model=Methodology)
async def methodology():
    """One-call methodology payload for manual verification and reviewers."""
    return {
        "validation": await validation(),
        "provenance": PROVENANCE,
        "views": await views(),
    }
