"""Methodology & validation -- proves the data is sound and shows provenance."""
from fastapi import APIRouter
from ..db import fetch_all

router = APIRouter(prefix="/api/methodology", tags=["methodology"])

PROVENANCE = {
    "source": "Synthetic, generated by a seeded Python model (generate_factory_data.py).",
    "no_proprietary_data": True,
    "seed": 1970,
    "reproducible": "Re-running the generator reproduces the dataset byte-for-byte.",
    "modeling": [
        "Weibull time-to-failure per asset class (wear-out, beta>1)",
        "Shift/crew variance with a night-shift handoff penalty",
        "Defect propagation: origin station vs detection station",
        "Year-over-year seasonal severity (no two summers alike)",
        "Robot replacements that reset the fault clock",
        "Permanent process changes + a model-year launch (event rediscovery)",
    ],
    "oee_definition": (
        "OEE = Availability x Performance x Quality. "
        "Availability = (planned_time - downtime) / planned_time; "
        "Quality = good_units / produced_units; "
        "Performance = produced / (planned * Availability). "
        "Identity check: OEE == good_units / planned_units."
    ),
}

# The view definitions backing each dashboard section (shown in the UI).
VIEW_SQL = {
    "OEE": "SELECT 100*(planned_time-downtime)/planned_time AS availability, "
           "100*good/produced AS quality, ... FROM fact_production  (see v_oee)",
    "Loss by station": "downtime hours by faulting-asset station FULL JOIN "
                       "scrap units by root_cause_station  (see v_loss_by_station)",
    "Root cause vs detection": "COUNT(*) GROUP BY root_cause_station vs "
                               "detected_station  (see v_rootcause_ranking / v_propagation)",
    "Replacement candidates": "faults this year vs last per robot, trend flag "
                              "(see v_robot_candidates)",
}


@router.get("/validation")
async def validation():
    """Row counts, referential-integrity checks, and reconciliation results."""
    return await fetch_all("SELECT check_name, v AS value, status FROM v_validation ORDER BY ord")


@router.get("/provenance")
async def provenance():
    return PROVENANCE


@router.get("/views")
async def views():
    return [{"section": k, "logic": v} for k, v in VIEW_SQL.items()]
